### ISSUE TITLE
`btcli w balance --all` stopped working in v3.0.0

### ISSUE THREAD

**Issue by noaonoszko** [opentensor/btwallet#85]
Works in v2.1.3 but not in v.3.0.0 and fails with
```bash
Using the wallet path from config: ~/.bittensor/wallets/
[Verbose]: Fetching data for all wallets

An unknown error has occurred: 'builtins.Keyfile' object has no attribute 'keypair'
Traceback (most recent call last):
  File "<some-path>/.venv/lib/python3.11/site-packages/bittensor_cli/cli.py", line 835, in _run
    result = await cmd
             ^^^^^^^^^
  File "<some-path>/.venv/lib/python3.11/site-packages/bittensor_cli/src/commands/wallets.py", line 267, in wallet_balance
    coldkeys, wallet_names = _get_coldkey_ss58_addresses_for_path(wallet.path)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<some-path>/.venv/lib/python3.11/site-packages/bittensor_cli/src/commands/wallets.py", line 239, in
_get_coldkey_ss58_addresses_for_path
    ss58_addresses = [Keyfile(path).keypair.ss58_address for path in coldkey_paths]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<some-path>/.venv/lib/python3.11/site-packages/bittensor_cli/src/commands/wallets.py", line 239, in <listcomp>
    ss58_addresses = [Keyfile(path).keypair.ss58_address for path in coldkey_paths]
                      ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'builtins.Keyfile' object has no attribute 'keypair'
```
when running with `--verbose`.
 
This error only occurs for me when I use the `--all` flag.

I am using the following versions of related packages:
```bash
bittensor                 8.5.1
bittensor-cli             8.4.2
bittensor-commit-reveal   0.1.0
bt-decode                 0.4.0
```

**Comment by roman-opentensor** [comment]
fixed in 3.0.3
